#!/bin/sh

echo "------------- docker-compose up -d -------------"
docker-compose up -d
echo

echo "------------- docker-compose ps -------------"
docker-compose ps
echo

exec_in_vault() {
  echo "------------- $@ -------------"
  docker-compose exec -T vault "$@"
  echo
}

exec_in_vault vault auth "$(docker-compose logs vault | grep 'Root Token:' | tail -n 1 | awk '{ print $NF }')"
exec_in_vault vault status
exec_in_vault vault auth-enable userpass
exec_in_vault vault policy-write admin /app/admin.hcl
exec_in_vault vault write auth/userpass/users/test password=test policies=admin
exec_in_vault vault write secret/test somekey=somedata

echo "------------- Vault Root Token -------------"
docker-compose logs vault | grep 'Root Token:' | tail -n 1
